In [1]:
#First, please run this cell and restart your kernel.
#These are all the libraries you need for this python notebook.

%pip install pandas
%pip install numpy
%pip install scipy
%pip install seaborn
%pip install matplotlib
%pip install sklearn
%pip install plotly

%pip install --upgrade pandas
%pip install --upgrade numpy
%pip install --upgrade scipy
%pip install --upgrade seaborn
%pip install --upgrade matplotlib
%pip install --upgrade sklearn
%pip install --upgrade plotly

Requirement already satisfied: pandas in c:\users\omen\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\omen\anaconda3\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\omen\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\omen\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\omen\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\omen\anaconda3\lib\site-packages (1.22.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scipy in c:\users\omen\anaconda3\lib\site-packages (1.8.1)
Requirement already satisfied: numpy<1.25.0,>=1.17.3 in c:\users\omen\anaconda3\lib\site-packages (from scipy) (1.22.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\users\omen\anaconda3\lib\site-packages (0.11.2)
Requirement already satisfied: numpy>=1.15 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (1.22.4)
Requirement already satisfied: matplotlib>=2.2 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (3.5.2)
Requirement already satisfied: pandas>=0.23 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (1.4.2)
Requirement already satisfied: scipy>=1.0 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (1.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.0.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: packaging>=20.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.4)
Requirement already satisfied: cycler>=0.10 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.25.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\omen\anaconda3\lib\site-packages (from pandas>=0.23->seaborn) (2021.3)

Requirement already satisfied: six>=1.5 in c:\users\omen\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
Requirement already satisfied: matplotlib in c:\users\omen\anaconda3\lib\site-packages (3.5.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (1.3.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: cycler>=0.10 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (9.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: numpy>=1.17 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (1.22.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (3.0.4)
Requirement already satisfied: six>=1.5 in c:\users\omen\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: sklearn in c:\users\omen\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\omen\anaconda3\lib\site-packages (from sklearn) (1.0.2)
Requirement already satisfied: numpy>=1.14.6 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.22.4)
Requirement already satisfied: joblib>=0.11 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.8.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: plotly in c:\users\omen\anaconda3\lib\site-packages (5.8.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\omen\anaconda3\lib\site-packages (from plotly) (8.0.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in c:\users\omen\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\omen\anaconda3\lib\site-packages (from pandas) (1.22.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\omen\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\omen\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\omen\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\omen\anaconda3\lib\site-packages (1.22.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scipy in c:\users\omen\anaconda3\lib\site-packages (1.8.1)
Requirement already satisfied: numpy<1.25.0,>=1.17.3 in c:\users\omen\anaconda3\lib\site-packages (from scipy) (1.22.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\users\omen\anaconda3\lib\site-packages (0.11.2)
Requirement already satisfied: matplotlib>=2.2 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (3.5.2)
Requirement already satisfied: pandas>=0.23 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (1.4.2)
Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy>=1.15 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (1.22.4)
Requirement already satisfied: scipy>=1.0 in c:\users\omen\anaconda3\lib\site-packages (from seaborn) (1.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.0.1)
Requirement already satisfied: cycler>=0.10 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (21.3)

Requirement already satisfied: fonttools>=4.22.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.3.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\omen\anaconda3\lib\site-packages (from pandas>=0.23->seaborn) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\omen\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
Requirement already satisfied: matplotlib in c:\users\omen\anaconda3\lib\site-packages (3.5.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (9.0.1)
Requirement already satisfied: cycler>=0.10 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: packaging>=20.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (3.0.4)
Requirement already satisfied: numpy>=1.17 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (1.22.4)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\omen\anaconda3\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: six>=1.5 in c:\users\omen\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: sklearn in c:\users\omen\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\omen\anaconda3\lib\site-packages (from sklearn) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (2.2.0)
Requirement already satisfied: numpy>=1.14.6 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.22.4)
Requirement already satisfied: scipy>=1.1.0 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.8.1)
Requirement already satisfied: joblib>=0.11 in c:\users\omen\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.1.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: plotly in c:\users\omen\anaconda3\lib\site-packages (5.8.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\omen\anaconda3\lib\site-packages (from plotly) (8.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import normaltest
from scipy import stats


#Libraries for model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [3]:
#this function is to read, transform and join 2 data frame
#%%
def read_secom():
    path = ('C:/Users/OMEN/Downloads/secom.data')
    df = pd.read_csv(path, delimiter=' ', header=None, na_values=['NaN'])
    df.columns = ['feature'+str(x+1) for x in range(len(df.columns))]
    return df


#%%
def read_labels():
    path = ('C:/Users/OMEN/Downloads/secom_labels.data')
    df = pd.read_csv(path, delimiter=' ', header=None, na_values=['NaN'])
    df.columns = ['status','timestamp']
    df['timestamp'] = pd.to_datetime(df['timestamp'],dayfirst=True)
    return df

#read 2 df 
df_features = read_secom()
df_target = read_labels()

#concat them vertically
df = pd.concat([df_features,df_target],axis=1)

df.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature583,feature584,feature585,feature586,feature587,feature588,feature589,feature590,status,timestamp
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN,-1,2008-07-19 11:55:00
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045,-1,2008-07-19 12:32:00
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602,1,2008-07-19 13:17:00
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432,-1,2008-07-19 14:43:00
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432,-1,2008-07-19 15:22:00

In [4]:
# Drop duplicate columns

In [5]:
df2 = df.T.groupby(level=0).first().T

In [6]:
print(df2)

     feature1 feature10 feature100 feature101 feature102 feature103  \
0     3030.93    0.0162    -0.0251     0.0002     0.0002      0.135
1     3095.78   -0.0005    -0.0158    -0.0004    -0.0004    -0.0752
2     2932.61    0.0041     0.1218     0.0006    -0.0001     0.0134
3     2988.72   -0.0124    -0.0195    -0.0002        0.0    -0.0699
4     3032.24   -0.0031    -0.0167     0.0004    -0.0003     0.0696
...       ...       ...        ...        ...        ...        ...
1562  2899.41   -0.0045     0.0884        0.0        0.0    -0.0988
1563  3052.31   -0.0061    -0.0372    -0.0004     0.0002     0.0855
1564  2978.81      None    -0.0177    -0.0001    -0.0002     0.0022
1565  2894.92   -0.0072     0.1451     0.0004        0.0    -0.1165
1566  2944.92      None    -0.0632     0.0002        0.0    -0.1077

     feature104 feature105 feature106 feature107  ... feature92 feature93  \
0       -0.0042     0.0003     0.0056        0.0  ...   -0.3274   -0.0055
1       -0.0045     0.0002     0.0015        0.0  ...    0.1455   -0.0015
2       -0.0026    -0.0016    -0.0006     0.0013  ...    0.0553    0.0006
3       -0.0059     0.0003     0.0003     0.0021  ...    0.0697   -0.0003
4       -0.0045     0.0002     0.0078        0.0  ...    0.0448   -0.0077
...         ...        ...        ...        ...  ...       ...       ...
1562    -0.0094    -0.0012    -0.0002    -0.0011  ...    0.1671    0.0002
1563    -0.0116     0.0005     0.0055    -0.0026  ...    -0.357   -0.0055
1564    -0.0142     0.0002    -0.0033     0.0001  ...   -0.0223    0.0034
1565    -0.0087    -0.0019     0.0036     0.0035  ...    0.1759   -0.0036
1566    -0.0102     0.0008     0.0009     0.0009  ...    0.1756   -0.0009

     feature94 feature95 feature96 feature97 feature98 feature99 status  \
0      -0.0001    0.0001    0.0003   -0.2786       0.0    0.3974     -1
1          0.0   -0.0005    0.0001    0.5854       0.0   -0.9353     -1
2      -0.0013       0.0    0.0002   -0.1343       0.0   -0.1427      1
3      -0.0021   -0.0001    0.0002    0.0411       0.0    0.0177     -1
4      -0.0001   -0.0001   -0.0001    0.2189       0.0   -0.6704     -1
...        ...       ...       ...       ...       ...       ...    ...
1562    0.0011       0.0       0.0   -0.0382       0.0     0.073     -1
1563    0.0026       0.0    0.0001   -0.0821       0.0    0.4289     -1
1564   -0.0001   -0.0002       0.0    0.2516       0.0   -0.4311     -1
1565   -0.0034       0.0    0.0001   -0.0926       0.0   -0.1023     -1
1566   -0.0009    0.0001       0.0   -0.0728       0.0    0.0291     -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]

In [7]:
# Use groupby() to drop duplicate columns

In [8]:
df2 = df.T.groupby(level=0).first().T
print(df2)

     feature1 feature10 feature100 feature101 feature102 feature103  \
0     3030.93    0.0162    -0.0251     0.0002     0.0002      0.135
1     3095.78   -0.0005    -0.0158    -0.0004    -0.0004    -0.0752
2     2932.61    0.0041     0.1218     0.0006    -0.0001     0.0134
3     2988.72   -0.0124    -0.0195    -0.0002        0.0    -0.0699
4     3032.24   -0.0031    -0.0167     0.0004    -0.0003     0.0696
...       ...       ...        ...        ...        ...        ...
1562  2899.41   -0.0045     0.0884        0.0        0.0    -0.0988
1563  3052.31   -0.0061    -0.0372    -0.0004     0.0002     0.0855
1564  2978.81      None    -0.0177    -0.0001    -0.0002     0.0022
1565  2894.92   -0.0072     0.1451     0.0004        0.0    -0.1165
1566  2944.92      None    -0.0632     0.0002        0.0    -0.1077

     feature104 feature105 feature106 feature107  ... feature92 feature93  \
0       -0.0042     0.0003     0.0056        0.0  ...   -0.3274   -0.0055
1       -0.0045     0.0002     0.0015        0.0  ...    0.1455   -0.0015
2       -0.0026    -0.0016    -0.0006     0.0013  ...    0.0553    0.0006
3       -0.0059     0.0003     0.0003     0.0021  ...    0.0697   -0.0003
4       -0.0045     0.0002     0.0078        0.0  ...    0.0448   -0.0077
...         ...        ...        ...        ...  ...       ...       ...
1562    -0.0094    -0.0012    -0.0002    -0.0011  ...    0.1671    0.0002
1563    -0.0116     0.0005     0.0055    -0.0026  ...    -0.357   -0.0055
1564    -0.0142     0.0002    -0.0033     0.0001  ...   -0.0223    0.0034
1565    -0.0087    -0.0019     0.0036     0.0035  ...    0.1759   -0.0036
1566    -0.0102     0.0008     0.0009     0.0009  ...    0.1756   -0.0009

     feature94 feature95 feature96 feature97 feature98 feature99 status  \
0      -0.0001    0.0001    0.0003   -0.2786       0.0    0.3974     -1
1          0.0   -0.0005    0.0001    0.5854       0.0   -0.9353     -1
2      -0.0013       0.0    0.0002   -0.1343       0.0   -0.1427      1
3      -0.0021   -0.0001    0.0002    0.0411       0.0    0.0177     -1
4      -0.0001   -0.0001   -0.0001    0.2189       0.0   -0.6704     -1
...        ...       ...       ...       ...       ...       ...    ...
1562    0.0011       0.0       0.0   -0.0382       0.0     0.073     -1
1563    0.0026       0.0    0.0001   -0.0821       0.0    0.4289     -1
1564   -0.0001   -0.0002       0.0    0.2516       0.0   -0.4311     -1
1565   -0.0034       0.0    0.0001   -0.0926       0.0   -0.1023     -1
1566   -0.0009    0.0001       0.0   -0.0728       0.0    0.0291     -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]

In [9]:
# Remove duplicate columns pandas DataFrame
df2 = df.loc[:,~df.columns.duplicated()]
print(df2)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]

In [10]:
# Remove repeted columns in a DataFrame
df2 = df.loc[:,~df.T.duplicated(keep='first')]
print(df2)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 488 columns]

In [11]:
# keep last duplicate columns
df2 = df.loc[:,~df.T.duplicated(keep='last')]
print(df2)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 488 columns]

In [12]:
# Use DataFrame.columns.duplicated() to drop duplicate columns
duplicate_cols = df.columns[df.columns.duplicated()]
df.drop(columns=duplicate_cols, inplace=True)
print(df)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]

In [13]:
# Drop duplicate columns
df2 = df.T.drop_duplicates().T
print(df2)

     feature1 feature2   feature3   feature4 feature5 feature6  feature7  \
0     3030.93   2564.0  2187.7333  1411.1265   1.3602    100.0   97.6133
1     3095.78  2465.14  2230.4222  1463.6606   0.8294    100.0  102.3433
2     2932.61  2559.94  2186.4111  1698.0172   1.5102    100.0   95.4878
3     2988.72   2479.9  2199.0333   909.7926   1.3204    100.0  104.2367
4     3032.24  2502.87  2233.3667    1326.52   1.5334    100.0  100.3967
...       ...      ...        ...        ...      ...      ...       ...
1562  2899.41  2464.36  2179.7333  3085.3781   1.4843    100.0   82.2467
1563  3052.31  2522.55  2198.5667  1124.6595   0.8763    100.0   98.4689
1564  2978.81  2379.78     2206.3  1110.4967   0.8236    100.0   99.4122
1565  2894.92  2532.01  2177.0333  1183.7287   1.5726    100.0   98.7978
1566  2944.92  2450.76  2195.4444  2914.1792   1.5978    100.0   85.1011

     feature8 feature9 feature10  ... feature583 feature584 feature585  \
0      0.1242   1.5005    0.0162  ...     0.5005     0.0118     0.0035
1      0.1247   1.4966   -0.0005  ...     0.5019     0.0223     0.0055
2      0.1241   1.4436    0.0041  ...     0.4958     0.0157     0.0039
3      0.1217   1.4882   -0.0124  ...      0.499     0.0103     0.0025
4      0.1235   1.5031   -0.0031  ...       0.48     0.4766     0.1045
...       ...      ...       ...  ...        ...        ...        ...
1562   0.1248   1.3424   -0.0045  ...     0.4988     0.0143     0.0039
1563   0.1205   1.4333   -0.0061  ...     0.4975     0.0131     0.0036
1564   0.1208      NaN       NaN  ...     0.4987     0.0153     0.0041
1565   0.1213   1.4622   -0.0072  ...     0.5004     0.0178     0.0038
1566   0.1235      NaN       NaN  ...     0.4987     0.0181      0.004

     feature586 feature587 feature588 feature589 feature590 status  \
0         2.363        NaN        NaN        NaN        NaN     -1
1        4.4447     0.0096     0.0201      0.006   208.2045     -1
2        3.1745     0.0584     0.0484     0.0148    82.8602      1
3        2.0544     0.0202     0.0149     0.0044    73.8432     -1
4       99.3032     0.0202     0.0149     0.0044    73.8432     -1
...         ...        ...        ...        ...        ...    ...
1562     2.8669     0.0068     0.0138     0.0047    203.172     -1
1563     2.6238     0.0068     0.0138     0.0047    203.172     -1
1564      3.059     0.0197     0.0086     0.0025    43.5231     -1
1565     3.5662     0.0262     0.0245     0.0075    93.4941     -1
1566     3.6275     0.0117     0.0162     0.0045   137.7844     -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 488 columns]

In [14]:

# Use groupby() to drop duplicate columns
df2 = df.T.groupby(level=0).first().T
print(df2)

     feature1 feature10 feature100 feature101 feature102 feature103  \
0     3030.93    0.0162    -0.0251     0.0002     0.0002      0.135
1     3095.78   -0.0005    -0.0158    -0.0004    -0.0004    -0.0752
2     2932.61    0.0041     0.1218     0.0006    -0.0001     0.0134
3     2988.72   -0.0124    -0.0195    -0.0002        0.0    -0.0699
4     3032.24   -0.0031    -0.0167     0.0004    -0.0003     0.0696
...       ...       ...        ...        ...        ...        ...
1562  2899.41   -0.0045     0.0884        0.0        0.0    -0.0988
1563  3052.31   -0.0061    -0.0372    -0.0004     0.0002     0.0855
1564  2978.81      None    -0.0177    -0.0001    -0.0002     0.0022
1565  2894.92   -0.0072     0.1451     0.0004        0.0    -0.1165
1566  2944.92      None    -0.0632     0.0002        0.0    -0.1077

     feature104 feature105 feature106 feature107  ... feature92 feature93  \
0       -0.0042     0.0003     0.0056        0.0  ...   -0.3274   -0.0055
1       -0.0045     0.0002     0.0015        0.0  ...    0.1455   -0.0015
2       -0.0026    -0.0016    -0.0006     0.0013  ...    0.0553    0.0006
3       -0.0059     0.0003     0.0003     0.0021  ...    0.0697   -0.0003
4       -0.0045     0.0002     0.0078        0.0  ...    0.0448   -0.0077
...         ...        ...        ...        ...  ...       ...       ...
1562    -0.0094    -0.0012    -0.0002    -0.0011  ...    0.1671    0.0002
1563    -0.0116     0.0005     0.0055    -0.0026  ...    -0.357   -0.0055
1564    -0.0142     0.0002    -0.0033     0.0001  ...   -0.0223    0.0034
1565    -0.0087    -0.0019     0.0036     0.0035  ...    0.1759   -0.0036
1566    -0.0102     0.0008     0.0009     0.0009  ...    0.1756   -0.0009

     feature94 feature95 feature96 feature97 feature98 feature99 status  \
0      -0.0001    0.0001    0.0003   -0.2786       0.0    0.3974     -1
1          0.0   -0.0005    0.0001    0.5854       0.0   -0.9353     -1
2      -0.0013       0.0    0.0002   -0.1343       0.0   -0.1427      1
3      -0.0021   -0.0001    0.0002    0.0411       0.0    0.0177     -1
4      -0.0001   -0.0001   -0.0001    0.2189       0.0   -0.6704     -1
...        ...       ...       ...       ...       ...       ...    ...
1562    0.0011       0.0       0.0   -0.0382       0.0     0.073     -1
1563    0.0026       0.0    0.0001   -0.0821       0.0    0.4289     -1
1564   -0.0001   -0.0002       0.0    0.2516       0.0   -0.4311     -1
1565   -0.0034       0.0    0.0001   -0.0926       0.0   -0.1023     -1
1566   -0.0009    0.0001       0.0   -0.0728       0.0    0.0291     -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]

In [15]:
# Remove duplicate columns pandas DataFrame
df2 = df.loc[:,~df.columns.duplicated()]
print(df2)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]

In [16]:
# Remove repeted columns in a DataFrame
df2 = df.loc[:,~df.T.duplicated(keep='first')]
print(df2)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 488 columns]

In [17]:
# Use DataFrame.columns.duplicated() to drop duplicate columns
duplicate_cols = df.columns[df.columns.duplicated()]
df.drop(columns=duplicate_cols, inplace=True)
print(df)

      feature1  feature2   feature3   feature4  feature5  feature6  feature7  \
0      3030.93   2564.00  2187.7333  1411.1265    1.3602     100.0   97.6133
1      3095.78   2465.14  2230.4222  1463.6606    0.8294     100.0  102.3433
2      2932.61   2559.94  2186.4111  1698.0172    1.5102     100.0   95.4878
3      2988.72   2479.90  2199.0333   909.7926    1.3204     100.0  104.2367
4      3032.24   2502.87  2233.3667  1326.5200    1.5334     100.0  100.3967
...        ...       ...        ...        ...       ...       ...       ...
1562   2899.41   2464.36  2179.7333  3085.3781    1.4843     100.0   82.2467
1563   3052.31   2522.55  2198.5667  1124.6595    0.8763     100.0   98.4689
1564   2978.81   2379.78  2206.3000  1110.4967    0.8236     100.0   99.4122
1565   2894.92   2532.01  2177.0333  1183.7287    1.5726     100.0   98.7978
1566   2944.92   2450.76  2195.4444  2914.1792    1.5978     100.0   85.1011

      feature8  feature9  feature10  ...  feature583  feature584  feature585  \
0       0.1242    1.5005     0.0162  ...      0.5005      0.0118      0.0035
1       0.1247    1.4966    -0.0005  ...      0.5019      0.0223      0.0055
2       0.1241    1.4436     0.0041  ...      0.4958      0.0157      0.0039
3       0.1217    1.4882    -0.0124  ...      0.4990      0.0103      0.0025
4       0.1235    1.5031    -0.0031  ...      0.4800      0.4766      0.1045
...        ...       ...        ...  ...         ...         ...         ...
1562    0.1248    1.3424    -0.0045  ...      0.4988      0.0143      0.0039
1563    0.1205    1.4333    -0.0061  ...      0.4975      0.0131      0.0036
1564    0.1208       NaN        NaN  ...      0.4987      0.0153      0.0041
1565    0.1213    1.4622    -0.0072  ...      0.5004      0.0178      0.0038
1566    0.1235       NaN        NaN  ...      0.4987      0.0181      0.0040

      feature586  feature587  feature588  feature589  feature590  status  \
0         2.3630         NaN         NaN         NaN         NaN      -1
1         4.4447      0.0096      0.0201      0.0060    208.2045      -1
2         3.1745      0.0584      0.0484      0.0148     82.8602       1
3         2.0544      0.0202      0.0149      0.0044     73.8432      -1
4        99.3032      0.0202      0.0149      0.0044     73.8432      -1
...          ...         ...         ...         ...         ...     ...
1562      2.8669      0.0068      0.0138      0.0047    203.1720      -1
1563      2.6238      0.0068      0.0138      0.0047    203.1720      -1
1564      3.0590      0.0197      0.0086      0.0025     43.5231      -1
1565      3.5662      0.0262      0.0245      0.0075     93.4941      -1
1566      3.6275      0.0117      0.0162      0.0045    137.7844      -1

               timestamp
0    2008-07-19 11:55:00
1    2008-07-19 12:32:00
2    2008-07-19 13:17:00
3    2008-07-19 14:43:00
4    2008-07-19 15:22:00
...                  ...
1562 2008-10-16 15:13:00
1563 2008-10-16 20:49:00
1564 2008-10-17 05:26:00
1565 2008-10-17 06:01:00
1566 2008-10-17 06:07:00

[1567 rows x 592 columns]